# Generated by Django 4.1 on 2024-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NextLevelOlympian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=30, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('school_number', models.CharField(max_length=255)),
                ('olympic_science', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('pinfl', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'olympians',
            },
        ),
        migrations.CreateModel(
            name='OlympicDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympic_science', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('empty', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'olympic_dates',
            },
        ),
    ]
