# Generated by Django 4.1 on 2024-05-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad2', '0004_nextlevelolympian_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextlevelolympian',
            name='status',
            field=models.CharField(default='go', max_length=100),
        ),
    ]
