# Generated by Django 5.0.2 on 2024-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
