# Generated by Django 5.0.2 on 2024-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_testresult_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, related_name='test_questions', to='test_app.test'),
        ),
    ]
