# Generated by Django 5.0.2 on 2024-03-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_testquestion_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
