# Generated by Django 5.0.2 on 2024-03-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_testquestion_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
