# Generated by Django 5.0.2 on 2024-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_test_end_time_test_olympiad_test_test_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='certificate_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='olympiad_test',
            field=models.BooleanField(default=False),
        ),
    ]
