# Generated by Django 5.0.2 on 2024-03-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_testresult_certificate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='olympiad_test',
        ),
    ]
