# Generated by Django 4.2.11 on 2024-04-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_remove_testresult_olympiad_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='test',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_questions', to='test_app.test'),
        ),
    ]
