# Generated by Django 4.2.11 on 2024-04-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_alter_testquestion_question_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='pinfl',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='school_number',
            field=models.CharField(max_length=100),
        ),
    ]
