# Generated by Django 4.2.11 on 2024-04-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_alter_testresult_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='school_number',
            field=models.CharField(max_length=255),
        ),
    ]
