# Generated by Django 4.1 on 2024-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_alter_testresult_school_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
