# Generated by Django 4.1 on 2024-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_rename_test_testresult_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='interval_minute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
