# Generated by Django 5.0.1 on 2024-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='science',
            new_name='olimpia_science',
        ),
        migrations.AddField(
            model_name='customuser',
            name='science_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='science_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='science_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
