# Generated by Django 5.0.2 on 2024-03-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_science_customuser_olimpia_science_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
