# Generated by Django 5.0.2 on 2024-03-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='token',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='token',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
