# Generated by Django 5.0.2 on 2024-03-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_token_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='OlimpistUser',
        ),
    ]
