# Generated by Django 4.2.11 on 2024-04-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_olimpistuser_pinfl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olimpistuser',
            name='olimpia_science',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='olimpistuser',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='olimpistuser',
            name='school_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='olimpistuser',
            name='science_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='olimpistuser',
            name='science_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='olimpistuser',
            name='science_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='olimpistuser',
            name='tg_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
