# Generated by Django 4.2.11 on 2024-04-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_olimpistuser_olimpia_science_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olimpistuser',
            name='school_number',
            field=models.CharField(max_length=40),
        ),
    ]
