# Generated by Django 4.2.11 on 2024-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_olimpistuser_school_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olimpistuser',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
