# Generated by Django 4.2.11 on 2024-04-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_olimpistuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olimpistuser',
            name='school_number',
            field=models.CharField(max_length=255),
        ),
    ]
